auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  http_listen_address: 0.0.0.0
  grpc_listen_address: 0.0.0.0
  log_level: info

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    s3:
      endpoint: ${SPACES_ENDPOINT}
      bucketnames: ${SPACES_BUCKET}
      access_key_id: ${SPACES_ACCESS_KEY}
      secret_access_key: ${SPACES_SECRET_KEY}
      s3forcepathstyle: true
      insecure: false
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: loki_index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    cache_ttl: 24h

  aws:
    s3: ${SPACES_ENDPOINT}
    bucketnames: ${SPACES_BUCKET}
    access_key_id: ${SPACES_ACCESS_KEY}
    secret_access_key: ${SPACES_SECRET_KEY}
    s3forcepathstyle: true
    insecure: false

limits_config:
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  max_streams_per_user: 10000
  max_global_streams_per_user: 50000
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  retention_period: 744h

compactor:
  working_directory: /loki/compactor
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  delete_request_store: s3

# Disable analytics
analytics:
  reporting_enabled: false

# Frontend for query splitting
frontend:
  encoding: protobuf

# Limits to prevent abuse
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_cache_freshness_per_query: 10m
  split_queries_by_interval: 15m
